all: main search sort prm pointutils arrayutils

main:
	javac Main.java

search:
	javac algos/Search.java

sort:
	javac algos/Sort.java

prm:
	javac Graph/PRM.java

pointutils:
	javac utils/PointUtils.java

arrayutils:
	javac utils/ArrayUtils.java

clean:
	rm -f *.class algos/*.class utils/*.class Graph/*.class
