all: main search graph prm pointutils

main:
	javac Program.java

search:
	javac algos/Search.java

shortestpath:
	javac algos/ShortestPath.java

bfsanddijkstra:
	javac Graph/BFSandDijkstra.java

graph:
	javac Graph/Graph.java

prm:
	javac Graph/PRM.java

pointutils:
	javac utils/PointUtils.java

clean:
	rm -f *.class algos/*.class algos/graphs/*.class utils/*.class Graph/*.class
