all: main search sort path prm graph pointutils arrayutils

main:
	javac Program.java

search:
	javac algos/Search.java

sort:
	javac algos/Sort.java

path:
	javac algos/graphs/Path.java

prm:
	javac Graph/PRM.java

graph:
	javac Graph/Graph.java

pointutils:
	javac utils/PointUtils.java

arrayutils:
	javac utils/ArrayUtils.java

clean:
	rm -f *.class algos/*.class utils/*.class Graph/*.class
